-- educational_institutions.establishment_code / activation_password were the
-- other half of the dead activation scheme (EstablishmentActivationService,
-- already stripped down) — generated by admin UI, never verified by any real
-- signup/login flow (students pick their establishment by search, not by
-- entering a code). Confirmed: the two existing rows' uai/code values are
-- also random-generated placeholders (EstablishmentCodeManager.jsx, removed),
-- not real official UAI codes — left in place as-is since dropping them
-- touches broader search/display code out of scope for this cleanup.
ALTER TABLE public.educational_institutions
  DROP COLUMN IF EXISTS establishment_code,
  DROP COLUMN IF EXISTS activation_password;
